# Plugin made by QuangDev05
# Plugin is already at version '${project.version}'
# Facebook: https://www.facebook.com/quangdev05.2024
# Discord: quangdev05
# Discord Community: https://discord.gg/MdgvJnegbM
# Github: https://github.com/PhamQuang2008/ClearLag24
# Spigot: https://www.spigotmc.org/resources/clearlag24.117080/
# BuiltByBit: https://builtbybit.com/resources/clearlag24.45790/
settings:
  # Set the time interval (in seconds) between automatic item deletions
  clear-interval: 480
  # Notification will be sent to all players before item removal
  broadcast-message: "All ground items have been removed to optimize server performance."
  # List of worlds from which the plugin will remove items
  worlds:
    - world
    - world_nether
    - world_the_end
  # If set to true, the plugin will remove items from all worlds. Set to false to delete only in the worlds listed above
  clear-all-worlds: false
  # Add the world to the blacklist so the plugin doesn't remove items there.
  blacklist:
    worlds:
      - your_custom_world
  # Add the names of the items you want to blacklist here, one item per line.
  # When added to the blacklist, the item will not be removed from the ground.
  items:
    - DIAMOND_SWORD
    - GOLDEN_APPLE